---
engines:
  duplication:
    enabled: true
    exclude_fingerprints:
    - 7350831d9d76e19bc04060f5be50d25b
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
    exclude_fingerprints:
    checks:
      no-eval:
        enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
  - "screeps-profiler.js"
  - "src/03 - Roles.js"

